export class LojinhaModel {
  getProdutos() {
    return [
      {
        id: 1,
        nome: 'Necessaire transparente',
        preco: 35.0,
        imagem: 'src/assets/lojinha/bolsinha.jpeg',
        categoria: 'acessorios',
        descricao: 'Necessaire linda e prática para organizar seus itens pessoais.',
      },
      {
        id: 2,
        nome: 'Estojo Autocuidado',
        preco: 28.0,
        imagem: 'src/assets/lojinha/estojo-autocuidado.jpeg',
        categoria: 'acessorios',
        descricao: 'Estojo especial para seus produtos de autocuidado. Ideal para fazer kits de higiene, maquiagem, manicure e muito mais!',
      },
      {
        id: 5,
        nome: 'Copo Térmico Personalizado',
        preco: 30.0,
        imagem: 'src/assets/lojinha/produto1.jpg',
        categoria: 'acessorios',
        descricao: 'Copo térmico personalizado com nome, ideal para manter sua bebida na temperatura certa!',
      },
      {
        id: 6,
        nome: 'Canetas Personalizadas',
        preco: 55.0,
        imagem: 'src/assets/lojinha/produto2.jpg',
        categoria: 'acessorios',
        descricao: 'Canetas personalizadas com o tema de sua preferência, perfeitas para lembrancinhas ou uso diário.',
      },
      {
        id: 7,
        nome: 'Necessaire Maletinha',
        preco: 40.0,
        imagem: 'src/assets/lojinha/produto3.jpg',
        categoria: 'acessorios',
        descricao: 'Necessaire em formato de maletinha com transparência frontal e personalizada. Ideal para organizar seus itens de forma prática e estilosa. É só escolher o tema e nós fazemos para você!',
      },
      {
        id: 8,
        nome: 'Camisa Sublimada',
        preco: 32.0,
        imagem: 'src/assets/lojinha/produto4.jpg',
        categoria: 'roupas',
        descricao: 'Camisa sublimada personalizada com o tema de sua escolha. Confortável e estilosa, perfeita para qualquer ocasião.',
      },
      {
        id: 10,
        nome: 'Marca páginas Personalizados',
        preco: 65.0,
        imagem: 'src/assets/lojinha/produto6.jpg',
        categoria: 'papelaria',
        descricao: 'Marca páginas personalizados com o tema de sua escolha. Ótimos para presentear ou usar no dia a dia.',
      },
      {
        id: 11,
        nome: 'Necessaire transparente',
        preco: 85.0,
        imagem: 'src/assets/lojinha/produto9.jpg',
        categoria: 'acessorios',
        descricao: 'Necessaire linda e prática para organizar seus itens pessoais. Com design elegante e funcional, ideal para uso diário ou viagens.',
      },
      {
        id: 12,
        nome: 'Canecas Personalizadas',
        preco: 75.0,
        imagem: 'src/assets/lojinha/produto8.jpg',
        categoria: 'acessorios',
        descricao: 'Canecas personalizadas com o tema de sua escolha. Perfeitas para presentear ou para uso pessoal, trazendo um toque especial ao seu café ou chá.',
      },
      {
        id: 16,
        nome: 'Organizador de Gavetas',
        preco: 45.0,
        imagem: 'src/assets/lojinha/produto12.jpg',
        categoria: 'organizacao',
        descricao: 'Organizador de gavetas para roupas de bebê ou peças íntimas com 3 variações de formato e tamanho, personalizado para a sua necessidade. Ajuda a manter tudo no lugar e facilita na hora de escolher as roupinhas do dia.',
      },
      {
        id: 22,
        nome: 'Kit de Necessaires Impermeáveis',
        preco: 8.0,
        imagem: 'src/assets/lojinha/produto18.jpg',
        categoria: 'acessorios',
        descricao: 'Kit com 2 necessaires impermeáveis, espaçosas e perfeitas para organizar itens de higiene, maquiagem ou acessórios. Práticas e fáceis de limpar, ideais para viagens ou uso diário.',
      },
    ];
  }
}
